---
- name: Copy global configuration files
  copy:
    src: etc/{{ item }}
    dest: /etc/
    owner: root
    group: root
    mode: 0644
  with_items:
    - bash.bashrc
    - profile
    - inputrc

- name: Copy user default bash configuration files
  copy:
    src: etc/skel/{{ item }}
    dest: /etc/skel/
    owner: root
    group: root
    mode: 0644
  with_items:
      - .bash_logout
      - .bash_profile
      - .bashrc
      - .profile

- name: Copy bash configuration files for max
  copy:
    src: max/{{ item }}
    dest: /home/max/
    owner: max
    group: max
    mode: 0600
  with_items:
      - .bash_profile
      - .profile

- name: Placing .bashrc template for max
  template:
    src: max/.bashrc.j2
    dest: /home/max/.bashrc
    owner: max
    group: max
    mode: 0600

- name: Copy bash configuration files for root
  copy:
    src: root/{{ item }}
    dest: /root/
    owner: root
    group: root
    mode: 0600
  with_items:
    - .bash_profile
    - .bashrc
    - .profile
  tags: pacman

- name: Install some related packages
  pacman:
    name:
      - lesspipe
      - git
      - youtube-dl
      - openssh
      - tmux
      - gvim
    state: present
...
