---
- hosts: localhost
  connection: local
  gather_facts: no
  become: true
  become_user: root
  roles:
    - role: bash
      tags: [ 'bash', 'dotfiles' ]
    - role: users
      tags: [ 'users' ]
    - role: pacman
      tags: [ 'pacman' ]
    - role: systemd
...
