---
- hosts: localhost
  connection: local
  gather_facts: no
  become: true
  become_user: root
  vars:
    xdg_cache_home:
      max: /home/max/.cache
      root: /root/.cache
    xdg_config_home:
      max: /home/max/.config
      root: /root/.config
  roles:
    - role: bash
      tags: [ 'bash', 'dotfiles' ]
    - role: users
      tags: [ 'users' ]
    - role: pacman
      tags: [ 'pacman' ]
    - role: systemd
    - role: git
      tags: [ 'git', 'dotfiles' ]
    - role: tmux
      tags: [ 'tmux', 'dotfiles' ]
    - role: vim
      tags: [ 'vim', 'dotfiles' ]
    - role: xfce4
      tags: [ 'xfce4' ]
    - role: xorg
      tags: [ 'xorg' ]
    - role: networkmanager
      tags: [ 'network' ]
...
