---
- name: Include sysctl play
  import_tasks: sysctl.yml
  tags: sysctl

- name: Include resolved play
  import_tasks: resolved.yml
  tags: resolved

- name: Include journald play
  import_tasks: journald.yml
  tags: journald

- name: Include modprobe play
  import_tasks: modprobe.yml
  tags: modprobe
...
