---
- name: Place a config for systemd-resolved
  copy:
    src: systemd/resolved.conf
    dest: /etc/systemd/
    mode: 0644
    owner: root
    group: root
  notify: restart resolved

- name: Enable --now systemd-resolved
  systemd:
    name: systemd-resolved.service
    enabled: yes
    state: started
  register: resolved_service

- name: Activate the recommended mode of operation
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  when: resolved_service is changed
...
