---
- name: Install git
  pacman: name=git state=present

- name: Ensure git folder exists
  file: path=/home/max/.config/git state=directory

- name: Copy the configuration file
  copy:
    src: gitconfig
    dest: /home/max/.config/git/config
    owner: max
    group: max
    mode: 0600
...
