---
- name: Install git
  pacman: name=git state=present

- name: Ensure git folder exists
  file:
    path: "{{ xdg_config_home['max'] }}/git"
    state: directory
    owner: max
    group: max
    mode: 0700

- name: Copy the configuration file
  copy:
    src: gitconfig
    dest: "{{ xdg_config_home['max'] }}/git/config"
    owner: max
    group: max
    mode: 0600
...
