---
# tasks file for users
- name: "Place useradd settings"
  copy:
    src: useradd
    dest: /etc/default/useradd
    owner: root
    group: root
    mode: 0644

- name: "Add an unprivilaged user"
  user:
    name: max
    uid: 1000
    comment: Maxim Zaitsev
    create_home: yes
    group: max
    groups: wheel,users
    append: yes
    shell: /bin/bash
    password: "{{ '{{user_pass}}' | password_hash('sha512')}}"
    update_password: on_create
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: "Maxim Zaitsev (7aitsev@pm.me)"
    ssh_key_file: "{{ ssh_key_name }}"
    ssh_key_passphrase: "{{ ssh_pass }}"
