---
- name: Install tmux
  pacman: name=tmux state=present

- name: Ensure tmux folder exists
  file:
    path: "{{ xdg_config_home['max'] }}/tmux"
    state: directory
    owner: max
    group: max
    mode: 0700

- name: Copy the configuration file
  copy:
    src: tmux.conf
    dest: "{{ xdg_config_home['max'] }}/tmux/tmux.conf"
    owner: max
    group: max
    mode: 0600
...
